dist: bionic
language: cpp
compiler: g++

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.1.0/bazel_2.1.0-linux-x86_64.deb
  - sha256sum --check internal_tools/bazel_2.1.0-linux-x86_64.deb.sha256
  - sudo dpkg --install bazel_2.1.0-linux-x86_64.deb
  - sudo apt-get -y install libnuma-dev

script:
  - bazel test --sandbox_debug --verbose_failures --test_output=streamed ...
